testapp/urls.py
from django.urls import path
from .import views
app_name = "testapp"
urlpatterns = [
	path('', views.MainPageView.as_view(), name='main_page')
]

testdjango/urls.py
from django.contrib import admin
from django.urls import path, include
from testapp import views as myapp_views
from django.conf.urls import handler404
from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG: urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('testapp.urls')),
]
 
handler404 = 'testapp.views.error_404_view'

testapp/models.py
from django.db import models

# Create your models here.

testapp/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
# Create your views here.
class MainPageView(TemplateView):
	template_name = "testapp/main_page.html"


def error_404_view(request, exception):
    data = {"name": "ThePythonDjango.com"}
    return render(request,'testapp/error_404.html', data)
 

testapp/templates/testapp/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title> {% block title %} {% endblock %} </title>

	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="{% static 'css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="css/style.css" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>

</head>
<body>

  <nav class="light-blue lighten-1" role="navigation">
    <div class="container">
    <div class="row">
  <div class="col s2">
    
    <div class="nav-wrapper container"><a id="logo-container" href="{% url 'testapp:main_page' %}" class="brand-logo">My App</a>

    </div></div>

     
         
         
      <ul class="right hide-on-med-and-down">
      
       <li><a href="#">sdfds</a></li>
        
        	
      </ul>

      <ul id="nav-mobile" class="side-nav">
      
        	<li><a href="#">sdfdf</a></li>

     
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </li>
</ul>
</div>
  </nav>


  

{% block content %}
{% endblock content %}


{% block footer %}
<footer class="light-blue lighten-1" role="navigation">
<div class="footer-copyright">
      <div class="container">
      Made by <span class="#f57f17 yellow darken-4">     </span>
      </div>
    </div>
</footer>
{% endblock footer %}




 <!--  Scripts-->
  <script src="{% static 'js/jquery.js' %}"></script>
  <script src="{% static 'js/materialize.js' %}"></script>
  <script src="{% static 'js/init.js' %}"></script>
   <script src="{% static 'js/drop.js' %}"></script>
 

    <script src="{% static 'bootstrap/js/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    {% block javascript %}{% endblock %}
</body>
</html>

testapp/templates/testapp/error_404.html
<html>
  <head>
  </head>
  <body>
    <h1> This is a custom 404 error page which will 
         be shown instead of default 404 error page of Django everytime
         incorrect urls is entered in browser.
    </h1>
  </body>
</html>

testapp/templates/testapp/main_page.html
{% extends "testapp/base.html" %}

{% block title %} Main Page {% endblock %}

{% block content %}
<div class="container">
	<div class="row">
	<h1> This is Main Page </h1>
</div>
</div>

{% endblock content %}